# This is the network config written by 'subiquity'
network:
  ethernets:
    enp0s3:
      dhcp4: true
    enp0s8:
      dhcp4: false
      addresses: [192.168.5.1/24]
    enp0s9:
      dhcp4: false
      addresses: [192.168.10.10/24]
  version: 2
